version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adoorei
    working_dir: /application
    volumes:
      - .:/application
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: adoorei
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - adoorei

  db:
    image: mysql:latest
    container_name: adoorei-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: adoorei
      MYSQL_ROOT_PASSWORD: root
    networks:
      - adoorei

  nginx:
    image: nginx:alpine
    container_name: adoorei-nginx
    working_dir: /application
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - adoorei

networks:
  adoorei: